// app/layout.tsx
import "./globals.css";
import { Metadata } from "next";

import Header from "./component/layout/header/header";
import { Box } from "@mui/material";
import Footer from "./component/layout/footer/footer";

const HEADER_HEIGHT = 140;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <Box sx={{ marginTop: `${HEADER_HEIGHT}px`, minHeight: "100vh" }}>
          {children}
        </Box>
        <Footer />
      </body>
    </html>
  );
}
