import { Metadata } from "next";
import MediaSwiper from "@/app/component/ProjectCard/MediaSwiper"
import { Typography } from "@mui/material";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const files : string[] = ["introduction/iloveimgResized/picture.png","introduction/iloveimgResized/picture2.png","introduction/iloveimgResized/picture3.JPG","introduction/iloveimgResized/picture4.jpg","introduction/iloveimgResized/picture5.png"]

export default function Top() {
  return (
    <>
        <MediaSwiper files={files}></MediaSwiper>
        <Typography variant="h3" textAlign={"center"}>アクセスカウンター</Typography>
        <Typography variant="h4" textAlign={"center"}>100</Typography>

        <Typography variant="h3" textAlign={"center"}>最新のお知らせ</Typography>

        <Typography variant="h3" textAlign={"center"}>最新のブログ</Typography>
    </>
  );
}
