import { Metadata } from "next";
import Layout from "./layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Top() {
  return (
    <>
      <Layout>
        トップページ
      </Layout>
    </>
  );
}
