/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下書きブログデータベースにアイテムを挿入する
         * @description 新しい下書きブログ記事を作成します
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DraftCreateRequest"];
                    "multipart/form-data": {
                        title: string;
                        /** Format: date */
                        date: string;
                        content: string;
                        /** @description JSON配列文字列（例: ["Go","AWS"]） */
                        tags: string;
                        /** @description "true" / "false"（現状は保存時にfalse固定） */
                        isPublished?: string;
                        /**
                         * Format: binary
                         * @description 添付ファイル（フィールド名は任意だが、代表例として定義）
                         */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DraftCreateResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * （現状）IDでアイテムを取得する
         * @description 現状のLambda実装は GET_TABLE_NAME 環境変数で指定されたテーブルから id をキーに取得し、
         *     Post形式のJSONを返します（パスは /drafts/{id} だがレスポンスは Post）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 取得する下書きのID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 下書きブログデータベースから特定のアイテムを削除する
         * @description 指定されたIDを持つ下書きブログ記事を削除します
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 削除する下書きのID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Draft with ID {id} deleted successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ブログデータベースから全てのアイテムを取得する
         * @description DynamoDBテーブルをScanして全件返します（現状の実装は isPublished=true の絞り込みは行いません）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 下書き用データベースからブログデータベースにアイテムを挿入する
         * @description 下書きを本番用ブログデータベースに公開します
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostPublishRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostPublishResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ブログデータベースから特定のアイテムを取得する
         * @description 指定されたIDを持つブログ記事を取得します
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 取得する記事のID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlainError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 現状のLambda実装はエラー時にJSONではなくプレーンテキストを返します。
         *     API Gateway/CloudWatchの運用上はこの形式を正とします。
         */
        PlainError: string;
        Draft: {
            /**
             * Format: uuid
             * @description 下書きの一意なID
             * @example 21828f55-1bb6-4a2f-abcc-79e3453f0d8f
             */
            id?: string;
            /**
             * @description ブログ記事のタイトル
             * @example Example Post
             */
            title?: string;
            /**
             * Format: date
             * @description 記事の日付
             * @example 2025-08-26
             */
            date?: string;
            /**
             * @description 記事の本文
             * @example This is the content of my first blog post.
             */
            content?: string;
            /**
             * @description 記事に関連するタグ
             * @example [
             *       "Go",
             *       "AWS",
             *       "Lambda"
             *     ]
             */
            tags?: string[];
            /**
             * @description 公開状態
             * @example false
             */
            isPublished?: boolean;
            /**
             * @description Time to live (削除時のみ)
             * @example 10000000
             */
            ttl?: number;
            /**
             * @description S3に保存した添付ファイルのオブジェクトキー一覧（下書き作成時のみ）
             * @example [
             *       "21828f55-1bb6-4a2f-abcc-79e3453f0d8f/example.png"
             *     ]
             */
            attachmentFilePath?: string[];
        };
        DraftCreateRequest: {
            /**
             * @description ブログ記事のタイトル
             * @example Example Post
             */
            title: string;
            /**
             * Format: date
             * @description 記事の日付
             * @example 2025-08-26
             */
            date: string;
            /**
             * @description 記事の本文
             * @example This is the content of my first blog post.
             */
            content: string;
            /**
             * @description 記事に関連するタグ
             * @example [
             *       "Go",
             *       "AWS",
             *       "Lambda"
             *     ]
             */
            tags: string[];
            /**
             * @description 公開状態
             * @example false
             */
            isPublished?: boolean;
        };
        DraftCreateResponse: {
            /**
             * Format: uuid
             * @description 作成された下書きのID
             * @example 21828f55-1bb6-4a2f-abcc-79e3453f0d8f
             */
            id?: string;
        };
        Post: {
            /**
             * @description 記事の一意なID
             * @example id1
             */
            id?: string;
            /**
             * @description ブログ記事のタイトル
             * @example title
             */
            title?: string;
            /**
             * Format: date
             * @description 記事の日付
             * @example 2025-08-26
             */
            date?: string;
            /**
             * @description 記事の本文
             * @example content
             */
            content?: string;
            /**
             * @description 記事に関連するタグ
             * @example [
             *       "Android Studio"
             *     ]
             */
            tags?: string[];
            /**
             * @description 公開状態
             * @example false
             */
            isPublished?: boolean;
            /**
             * @description Time to live
             * @example 3600
             */
            ttl?: number;
        };
        PostPublishRequest: {
            /**
             * @description 公開する下書きのID
             * @example id
             */
            id: string;
            /**
             * @description 公開状態
             * @example true
             */
            isPublished: boolean;
        };
        PostPublishResponse: {
            /**
             * @description 公開された記事のID
             * @example id
             */
            id?: string;
            /**
             * @description 成功メッセージ
             * @example Blog post published successfully!
             */
            message?: string;
        };
        /**
         * @deprecated
         * @description 旧仕様。現状のLambda実装はエラー時にJSONではなくプレーンテキストを返すため、
         *     新規のレスポンス定義では PlainError (string) を使用します。
         */
        Error: {
            /**
             * @description エラーメッセージ
             * @example Invalid request body
             */
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
